rootProject.name = "avoid-project"
include("service")
include("gateway")
include("shared")
include("worklist")
include("worklist-ui")
include("analysis")
include("analysis-ui")
include("analysis-crawler")
include("report")
include("report-ui")
