spring:
  application.name: worklist-api
  main.web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery.root: /avoid-project
    stream:
      bindings:
        broadcast-worklist-events-in-0:
          destination: avoid-worklist-events
          group: broadcast-worklist-events
        publish-worklist-events-out-0.destination: avoid-worklist-events
      kafka:
        binder:
          brokers: gemini, pisces, aries, taurus, libra
          auto-add-partitions: true
  r2dbc:
    url: r2dbc:postgresql://gemini:5432/lims
    username: avoid
    password: avoid1004
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org.springframework.r2dbc: DEBUG


server:
  port: 0