spring:
  application:
    name: avoid-gateway-service
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery:
        root: /avoid-service
        register: false
    gateway:
      routes:
        - id: worklist-api
          uri: lb://worklist-api
          predicates:
            - Path=/worklist/**
        - id: sequencing-api
          uri: lb://sequencing-api
          predicates:
            - Path=/plates/**, /sequencing, /sequencing/**
        - id: analysis-api
          uri: lb://analysis-api
          predicates:
            - Path=/analysis/**
        - id: publish-api
          uri: lb://publish-api
          predicates:
            - Path=/samples/*/services/*/reports/*/publish
        - id: report-api
          uri: lb://report-api
          predicates:
            - Path=/samples/*/services/*/batch/*/row/*/print/*, /samples/*/services/*/reports/*, /samples/works, /samples/queue


server:
  resources : file:/data/lims/static/avoid-service/
  compression:
    enabled: true
    mime-types: text/javascript,application/javascript
    min-response-size: 2048
  port: 26040
