spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery:
        root: /RnD
    gateway:
      routes:
        - id: avoid-service
            uri: lb://avoid-service
          predicates:
            - Path=/avoid/**, /avoid.html, /avoid/*.js, /css/avoid.css
server:
  port: 26030