spring:
  application:
    name: publish-api
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: localhost:12181
      discovery:
        root: /avoid-service
    stream:
      default:
        max.message.bytes: 67109632
      function:
        definition: publish;broadcast-publishing
      bindings:
        publish-out-0.destination: report
        broadcast-publishing-in-0.destination: alis-pdf-publisher-response
      kafka:
        binder:
          brokers: localhost
          auto-add-partitions: true

  r2dbc:
    url: r2dbc:postgresql://172.19.216.212:5432/lims
    compatibility-mode : true
    username: avoid
    password: avoid1004
  data:
    cassandra:
      contact-points: 172.19.216.213
      local-datacenter: datacenter1
      username: gcgenome-superuser
      password: CvuvlrYXpi75SMjGfCcL7-9dKUIryACXAivIkrspuHszteuDj8weZQ
      port: 9042
      keyspace-name: lims
      schema-action: NONE
      connect-timeout-millis: 10000s
      read-timeout-millis: 10000s
      connect-timeout: 10000s
      read-timeout: 10000s
server:
  port: 29486

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

webhook:
  url: https://wh.jandi.com/connect-api/webhook/17558388/7ee4909d0db3e51da5990fbd032b6e34
