spring:
  application:
    name: publish-api
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: localhost:12181
      discovery:
        root: /avoid-service
    stream:
      default:
        max.message.bytes: 67109632
      function:
        definition: publishRms;broadcast-publishing
      bindings:
        publish-rms-out-o:
          destination: report
          group: report
        broadcast-publishing-in-0:
          destination: alis-pdf-publisher-response
          group: alis-pdf-publisher-response
      kafka:
        binder:
          brokers: localhost
          auto-add-partitions: true

  r2dbc:
    url: r2dbc:postgresql://gemini:5432/lims
    compatibility-mode : true
    username: avoid
    password: avoid1004
  data:
    cassandra:
      contact-points: gemini, pisces, taurus
      local-datacenter: datacenter1
      username: cassandra
      password: snubi1004
      port: 9042
      keyspace-name: lims
      schema-action: NONE
      connect-timeout-millis: 10000s
      read-timeout-millis: 10000s
      connect-timeout: 10000s
      read-timeout: 10000s
server:
  port: 58895

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

webhook:
  url: https://wh.jandi.com/connect-api/webhook/17558388/69834a4cb47d80f9c339a0ce83ab7c90
