spring:
  application.name: analysis-crawler
  main.web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://gemini:5432/lims
    compatibility-mode : true
    username: avoid
    password: avoid1004
server:
  port: 0
gcgenome:
  tmp-dir: /data/lims/tmp/AVOID/v1
  out-dir: /data/lims/processed-avoid