plugins {
    id "org.springframework.boot" version "2.6.2"
}
apply plugin: "java"
apply plugin: "io.spring.dependency-management"

group = "com.greencross"
version = "1.0"
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation project(":shared")
    implementation('org.springframework.boot:spring-boot-starter')
    implementation('org.springframework.boot:spring-boot-starter-batch')
    implementation('org.springframework.boot:spring-boot-starter-data-jpa')
    implementation('org.springframework.boot:spring-boot-starter-json')
    implementation('org.postgresql:postgresql')
    implementation('org.jsoup:jsoup:1.13.1')
    implementation('com.fasterxml.jackson.core:jackson-core:2.11.2')
    implementation('com.fasterxml.jackson.core:jackson-databind:2.11.2')
    implementation('org.projectlombok:lombok:1.18.12')
    annotationProcessor('org.projectlombok:lombok:1.18.12')
    implementation('com.google.guava:guava:30.0-jre')
    implementation('org.apache.httpcomponents:httpclient:4.5.13')
    implementation('org.apache.httpcomponents:httpmime:4.5.13')
    testImplementation('org.springframework.batch:spring-batch-test')
    testImplementation('org.springframework.boot:spring-boot-starter-test')
    testAnnotationProcessor('org.projectlombok:lombok:1.18.12')
    implementation('org.springframework.boot:spring-boot-starter-log4j2')
    testImplementation('com.h2database:h2')
}
configurations {
    all*.exclude group:'org.springframework.boot', module:'spring-boot-starter-logging'
}
bootJar {
    exclude('application.yml')
    archiveName "avoid-handler.jar"
}
clean.doFirst {
    delete "src/main/resources/static"
    delete "build/"
}