package com.greencross.lims.report.avoid.repository

import com.google.common.collect.Range
import com.google.common.collect.TreeRangeMap
import com.greencross.lims.report.builder.Sex
import org.springframework.stereotype.Repository
import java.util.*
import java.util.stream.Collectors

@Repository
class CancerRepo(
    private val ppv: Map<암종, TreeRangeMap<Int, Map<Sex, Double?>>>,
    private val asr: Map<암종, TreeRangeMap<Int, Map<Sex, Double?>>>
) {
    constructor() : this(
        mapOf(*Arrays.stream(암종.values()).map {
            val map: TreeRangeMap<Int, Map<Sex, Double?>> = TreeRangeMap.create()
            Pair(it, map)
        }.collect(Collectors.toList()).toTypedArray()),
        mapOf(*Arrays.stream(암종.values()).map {
            val map: TreeRangeMap<Int, Map<Sex, Double?>> = TreeRangeMap.create()
            Pair(it, map)
        }.collect(Collectors.toList()).toTypedArray())
    ) {
        //region #ppv
        ppv.get(암종.폐암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv.get(암종.폐암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv.get(암종.폐암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv.get(암종.폐암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.02)))
        ppv.get(암종.폐암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M,  0.04), Pair(Sex.F,  0.03)))
        ppv.get(암종.폐암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M,  0.06), Pair(Sex.F,  0.06)))
        ppv.get(암종.폐암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M,  0.10), Pair(Sex.F,  0.13)))
        ppv.get(암종.폐암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M,  0.22), Pair(Sex.F,  0.25)))
        ppv.get(암종.폐암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M,  0.44), Pair(Sex.F,  0.53)))
        ppv.get(암종.폐암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M,  0.91), Pair(Sex.F,  1.03)))
        ppv.get(암종.폐암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M,  1.96), Pair(Sex.F,  1.97)))
        ppv.get(암종.폐암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M,  4.13), Pair(Sex.F,  3.54)))
        ppv.get(암종.폐암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M,  8.27), Pair(Sex.F,  5.77)))
        ppv.get(암종.폐암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, 14.10), Pair(Sex.F,  7.42)))
        ppv.get(암종.폐암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, 19.77), Pair(Sex.F,  9.48)))
        ppv.get(암종.폐암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, 23.12), Pair(Sex.F, 10.26)))
        ppv.get(암종.폐암)?.put(Range.closed(80,84), mapOf(Pair(Sex.M, 23.09), Pair(Sex.F,  9.70)))
        ppv.get(암종.폐암)?.put(Range.closed(85,100),mapOf(Pair(Sex.M, 20.23), Pair(Sex.F,  7.62)))

        ppv.get(암종.대장암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv.get(암종.대장암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv.get(암종.대장암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv.get(암종.대장암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M,  0.02), Pair(Sex.F,  0.01)))
        ppv.get(암종.대장암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M,  0.04), Pair(Sex.F,  0.04)))
        ppv.get(암종.대장암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M,  0.08), Pair(Sex.F,  0.07)))
        ppv.get(암종.대장암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M,  0.19), Pair(Sex.F,  0.18)))
        ppv.get(암종.대장암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M,  0.48), Pair(Sex.F,  0.42)))
        ppv.get(암종.대장암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M,  1.00), Pair(Sex.F,  0.89)))
        ppv.get(암종.대장암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M,  1.81), Pair(Sex.F,  1.59)))
        ppv.get(암종.대장암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M,  3.66), Pair(Sex.F,  3.07)))
        ppv.get(암종.대장암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M,  6.51), Pair(Sex.F,  4.68)))
        ppv.get(암종.대장암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M, 11.57), Pair(Sex.F,  7.28)))
        ppv.get(암종.대장암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, 16.60), Pair(Sex.F,  9.76)))
        ppv.get(암종.대장암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, 23.17), Pair(Sex.F, 13.30)))
        ppv.get(암종.대장암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, 27.27), Pair(Sex.F, 16.18)))
        ppv.get(암종.대장암)?.put(Range.closed(80,84), mapOf(Pair(Sex.M, 31.18), Pair(Sex.F, 18.66)))
        ppv.get(암종.대장암)?.put(Range.closed(85,100),mapOf(Pair(Sex.M, 32.91), Pair(Sex.F, 18.05)))

        ppv.get(암종.간암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M,  0.04), Pair(Sex.F,  0.03)))
        ppv.get(암종.간암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M,  0.07), Pair(Sex.F,  0.08)))
        ppv.get(암종.간암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M,  0.08), Pair(Sex.F,  0.06)))
        ppv.get(암종.간암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M,  0.05), Pair(Sex.F,  0.07)))
        ppv.get(암종.간암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M,  0.04), Pair(Sex.F,  0.03)))
        ppv.get(암종.간암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M,  0.05), Pair(Sex.F,  0.03)))
        ppv.get(암종.간암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M,  0.11), Pair(Sex.F,  0.06)))
        ppv.get(암종.간암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M,  0.37), Pair(Sex.F,  0.18)))
        ppv.get(암종.간암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M,  0.92), Pair(Sex.F,  0.30)))
        ppv.get(암종.간암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M,  2.14), Pair(Sex.F,  0.57)))
        ppv.get(암종.간암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M,  4.55), Pair(Sex.F,  1.06)))
        ppv.get(암종.간암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M,  7.69), Pair(Sex.F,  1.83)))
        ppv.get(암종.간암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 11.31), Pair(Sex.F,  3.05)))
        ppv.get(암종.간암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 13.23), Pair(Sex.F,  4.33)))
        ppv.get(암종.간암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 14.61), Pair(Sex.F,  5.31)))
        ppv.get(암종.간암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 13.87), Pair(Sex.F,  5.39)))
        ppv.get(암종.간암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 12.51), Pair(Sex.F,  4.60)))
        ppv.get(암종.간암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 10.80), Pair(Sex.F,  3.36)))

        ppv.get(암종.췌장암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.01)))
        ppv.get(암종.췌장암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.01)))
        ppv.get(암종.췌장암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.02)))
        ppv.get(암종.췌장암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.04)))
        ppv.get(암종.췌장암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.06)))
        ppv.get(암종.췌장암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M, 0.02), Pair(Sex.F, 0.08)))
        ppv.get(암종.췌장암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M, 0.04), Pair(Sex.F, 0.08)))
        ppv.get(암종.췌장암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M, 0.10), Pair(Sex.F, 0.13)))
        ppv.get(암종.췌장암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M, 0.16), Pair(Sex.F, 0.16)))
        ppv.get(암종.췌장암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M, 0.24), Pair(Sex.F, 0.23)))
        ppv.get(암종.췌장암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 0.46), Pair(Sex.F, 0.38)))
        ppv.get(암종.췌장암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 0.84), Pair(Sex.F, 0.62)))
        ppv.get(암종.췌장암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 1.35), Pair(Sex.F, 1.00)))
        ppv.get(암종.췌장암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 1.97), Pair(Sex.F, 1.33)))
        ppv.get(암종.췌장암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 2.47), Pair(Sex.F, 1.84)))
        ppv.get(암종.췌장암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 2.61), Pair(Sex.F, 2.02)))
        ppv.get(암종.췌장암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 2.44), Pair(Sex.F, 1.82)))
        ppv.get(암종.췌장암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 2.39), Pair(Sex.F, 1.57)))

        ppv.get(암종.식도암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.01)))
        ppv.get(암종.식도암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.01)))
        ppv.get(암종.식도암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.01)))
        ppv.get(암종.식도암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.01)))
        ppv.get(암종.식도암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.01)))
        ppv.get(암종.식도암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.01)))
        ppv.get(암종.식도암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.01)))
        ppv.get(암종.식도암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.01)))
        ppv.get(암종.식도암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M,  0.02), Pair(Sex.F, 0.02)))
        ppv.get(암종.식도암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M,  0.09), Pair(Sex.F, 0.03)))
        ppv.get(암종.식도암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M,  0.29), Pair(Sex.F, 0.07)))
        ppv.get(암종.식도암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M,  0.77), Pair(Sex.F, 0.12)))
        ppv.get(암종.식도암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M,  1.73), Pair(Sex.F, 0.20)))
        ppv.get(암종.식도암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M,  3.03), Pair(Sex.F, 0.23)))
        ppv.get(암종.식도암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M,  4.08), Pair(Sex.F, 0.27)))
        ppv.get(암종.식도암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M,  4.91), Pair(Sex.F, 0.35)))
        ppv.get(암종.식도암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M,  4.90), Pair(Sex.F, 0.38)))
        ppv.get(암종.식도암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M,  3.65), Pair(Sex.F, 0.37)))

        ppv.get(암종.난소암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.01)))
        ppv.get(암종.난소암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.03)))
        ppv.get(암종.난소암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.11)))
        ppv.get(암종.난소암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.23)))
        ppv.get(암종.난소암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.51)))
        ppv.get(암종.난소암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.69)))
        ppv.get(암종.난소암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.84)))
        ppv.get(암종.난소암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.06)))
        ppv.get(암종.난소암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.37)))
        ppv.get(암종.난소암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.94)))
        ppv.get(암종.난소암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.61)))
        ppv.get(암종.난소암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.85)))
        ppv.get(암종.난소암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  3.07)))
        ppv.get(암종.난소암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.93)))
        ppv.get(암종.난소암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.81)))
        ppv.get(암종.난소암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.38)))
        ppv.get(암종.난소암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.74)))
        ppv.get(암종.난소암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.35)))

        ppv.get(암종.기타암종)?.put(Range.closed(0,   4), mapOf(Pair(Sex.M,  1.04), Pair(Sex.F,  0.89)))
        ppv.get(암종.기타암종)?.put(Range.closed(5,   9), mapOf(Pair(Sex.M,  2.21), Pair(Sex.F,  1.90)))
        ppv.get(암종.기타암종)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,  2.91), Pair(Sex.F,  2.49)))
        ppv.get(암종.기타암종)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,  3.68), Pair(Sex.F,  3.34)))
        ppv.get(암종.기타암종)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,  4.20), Pair(Sex.F,  5.17)))
        ppv.get(암종.기타암종)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,  5.47), Pair(Sex.F, 10.04)))
        ppv.get(암종.기타암종)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,  8.53), Pair(Sex.F, 18.69)))
        ppv.get(암종.기타암종)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M, 13.21), Pair(Sex.F, 29.82)))
        ppv.get(암종.기타암종)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M, 18.74), Pair(Sex.F, 40.45)))
        ppv.get(암종.기타암종)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M, 25.11), Pair(Sex.F, 49.28)))
        ppv.get(암종.기타암종)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M, 34.83), Pair(Sex.F, 56.59)))
        ppv.get(암종.기타암종)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M, 46.69), Pair(Sex.F, 61.23)))
        ppv.get(암종.기타암종)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M, 59.93), Pair(Sex.F, 64.90)))
        ppv.get(암종.기타암종)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 69.66), Pair(Sex.F, 65.83)))
        ppv.get(암종.기타암종)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 77.70), Pair(Sex.F, 67.55)))
        ppv.get(암종.기타암종)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 81.58), Pair(Sex.F, 67.56)))
        ppv.get(암종.기타암종)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 84.10), Pair(Sex.F, 67.51)))
        ppv.get(암종.기타암종)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 83.83), Pair(Sex.F, 63.72)))
        //endregion
        //region #asr
        asr.get(암종.폐암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,    0.1), Pair(Sex.F,   0.1)))
        asr.get(암종.폐암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,    0.2), Pair(Sex.F,   0.4)))
        asr.get(암종.폐암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,    0.2), Pair(Sex.F,   0.4)))
        asr.get(암종.폐암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,    0.5), Pair(Sex.F,   1.1)))
        asr.get(암종.폐암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,    2.3), Pair(Sex.F,   1.4)))
        asr.get(암종.폐암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,    3.3), Pair(Sex.F,   3.0)))
        asr.get(암종.폐암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,    5.2), Pair(Sex.F,   6.8)))
        asr.get(암종.폐암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   11.7), Pair(Sex.F,  13.3)))
        asr.get(암종.폐암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   24.1), Pair(Sex.F,  28.7)))
        asr.get(암종.폐암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,   49.8), Pair(Sex.F,  56.2)))
        asr.get(암종.폐암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  108.1), Pair(Sex.F, 108.7)))
        asr.get(암종.폐암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  232.8), Pair(Sex.F, 198.4)))
        asr.get(암종.폐암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  485.7), Pair(Sex.F, 330.3)))
        asr.get(암종.폐암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M,  880.6), Pair(Sex.F, 431.7)))
        asr.get(암종.폐암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 1315.5), Pair(Sex.F, 563.3)))
        asr.get(암종.폐암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 1601.4), Pair(Sex.F, 615.1)))
        asr.get(암종.폐암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 1598.4), Pair(Sex.F, 577.7)))
        asr.get(암종.폐암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 1353.7), Pair(Sex.F, 444.5)))

        asr.get(암종.대장암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,    0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.대장암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,    0.1), Pair(Sex.F,    0.1)))
        asr.get(암종.대장암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,    0.2), Pair(Sex.F,    0.4)))
        asr.get(암종.대장암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,    1.0), Pair(Sex.F,    0.7)))
        asr.get(암종.대장암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,    2.4), Pair(Sex.F,    2.3)))
        asr.get(암종.대장암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,    4.6), Pair(Sex.F,    4.0)))
        asr.get(암종.대장암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   11.1), Pair(Sex.F,   10.2)))
        asr.get(암종.대장암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   27.6), Pair(Sex.F,   23.9)))
        asr.get(암종.대장암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   57.9), Pair(Sex.F,   51.3)))
        asr.get(암종.대장암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  105.5), Pair(Sex.F,   92.7)))
        asr.get(암종.대장암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  217.3), Pair(Sex.F,  181.2)))
        asr.get(암종.대장암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  397.1), Pair(Sex.F,  280.6)))
        asr.get(암종.대장암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  744.0), Pair(Sex.F,  447.8)))
        asr.get(암종.대장암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 1127.0), Pair(Sex.F,  615.9)))
        asr.get(암종.대장암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 1697.7), Pair(Sex.F,  870.8)))
        asr.get(암종.대장암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 2102.7), Pair(Sex.F, 1093.1)))
        asr.get(암종.대장암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 2529.6), Pair(Sex.F, 1297.0)))
        asr.get(암종.대장암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 2732.6), Pair(Sex.F, 1245.7)))

        asr.get(암종.간암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M,   2.2), Pair(Sex.F,   1.6)))
        asr.get(암종.간암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M,   3.4), Pair(Sex.F,   3.9)))
        asr.get(암종.간암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M,   3.9), Pair(Sex.F,   2.8)))
        asr.get(암종.간암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M,   2.7), Pair(Sex.F,   3.6)))
        asr.get(암종.간암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M,   2.1), Pair(Sex.F,   1.7)))
        asr.get(암종.간암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M,   2.3), Pair(Sex.F,   1.6)))
        asr.get(암종.간암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M,   5.5), Pair(Sex.F,   3.1)))
        asr.get(암종.간암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M,  19.1), Pair(Sex.F,   9.3)))
        asr.get(암종.간암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M,  47.2), Pair(Sex.F,  15.3)))
        asr.get(암종.간암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M, 111.0), Pair(Sex.F,  29.2)))
        asr.get(암종.간암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M, 241.8), Pair(Sex.F,  54.2)))
        asr.get(암종.간암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M, 421.7), Pair(Sex.F,  94.5)))
        asr.get(암종.간암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M, 643.9), Pair(Sex.F, 159.5)))
        asr.get(암종.간암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, 768.8), Pair(Sex.F, 229.7)))
        asr.get(암종.간암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, 861.7), Pair(Sex.F, 284.0)))
        asr.get(암종.간암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, 811.3), Pair(Sex.F, 288.6)))
        asr.get(암종.간암)?.put(Range.closed(80,84), mapOf(Pair(Sex.M, 721.2), Pair(Sex.F, 244.2)))
        asr.get(암종.간암)?.put(Range.closed(85,89), mapOf(Pair(Sex.M, 611.7), Pair(Sex.F, 176.2)))

        asr.get(암종.췌장암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,   0.1), Pair(Sex.F,   0.0)))
        asr.get(암종.췌장암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,   0.2), Pair(Sex.F,   0.3)))
        asr.get(암종.췌장암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,   0.5), Pair(Sex.F,   1.2)))
        asr.get(암종.췌장암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,   0.7), Pair(Sex.F,   2.0)))
        asr.get(암종.췌장암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,   0.7), Pair(Sex.F,   3.0)))
        asr.get(암종.췌장암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,   1.0), Pair(Sex.F,   4.0)))
        asr.get(암종.췌장암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   1.8), Pair(Sex.F,   4.1)))
        asr.get(암종.췌장암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   4.8), Pair(Sex.F,   6.7)))
        asr.get(암종.췌장암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   7.9), Pair(Sex.F,   8.3)))
        asr.get(암종.췌장암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  11.9), Pair(Sex.F,  11.7)))
        asr.get(암종.췌장암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  23.5), Pair(Sex.F,  19.2)))
        asr.get(암종.췌장암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  42.9), Pair(Sex.F,  31.3)))
        asr.get(암종.췌장암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  68.8), Pair(Sex.F,  50.7)))
        asr.get(암종.췌장암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 101.2), Pair(Sex.F,  68.1)))
        asr.get(암종.췌장암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 127.4), Pair(Sex.F,  94.6)))
        asr.get(암종.췌장암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 134.7), Pair(Sex.F, 103.9)))
        asr.get(암종.췌장암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 125.8), Pair(Sex.F,  93.6)))
        asr.get(암종.췌장암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 123.4), Pair(Sex.F,  80.1)))

        asr.get(암종.식도암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.1)))
        asr.get(암종.식도암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,   0.2), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   0.1), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   0.5), Pair(Sex.F,  0.4)))
        asr.get(암종.식도암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   1.1), Pair(Sex.F,  1.2)))
        asr.get(암종.식도암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,   4.8), Pair(Sex.F,  1.8)))
        asr.get(암종.식도암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  15.7), Pair(Sex.F,  3.7)))
        asr.get(암종.식도암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  42.5), Pair(Sex.F,  6.7)))
        asr.get(암종.식도암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  95.9), Pair(Sex.F, 10.8)))
        asr.get(암종.식도암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 170.0), Pair(Sex.F, 12.7)))
        asr.get(암종.식도암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 231.7), Pair(Sex.F, 14.7)))
        asr.get(암종.식도암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 281.3), Pair(Sex.F, 19.3)))
        asr.get(암종.식도암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 280.4), Pair(Sex.F, 20.7)))
        asr.get(암종.식도암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 206.4), Pair(Sex.F, 20.1)))

        asr.get(암종.유방암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.유방암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.유방암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.유방암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.6)))
        asr.get(암종.유방암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    4.2)))
        asr.get(암종.유방암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,   25.1)))
        asr.get(암종.유방암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,  0.3), Pair(Sex.F,  115.5)))
        asr.get(암종.유방암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,  0.4), Pair(Sex.F,  340.3)))
        asr.get(암종.유방암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,  0.9), Pair(Sex.F,  793.7)))
        asr.get(암종.유방암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  1.9), Pair(Sex.F, 1433.1)))
        asr.get(암종.유방암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  2.6), Pair(Sex.F, 1948.1)))
        asr.get(암종.유방암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  5.8), Pair(Sex.F, 2100.8)))
        asr.get(암종.유방암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  7.2), Pair(Sex.F, 2152.2)))
        asr.get(암종.유방암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 10.8), Pair(Sex.F, 1864.2)))
        asr.get(암종.유방암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 14.4), Pair(Sex.F, 1633.5)))
        asr.get(암종.유방암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 17.5), Pair(Sex.F, 1231.9)))
        asr.get(암종.유방암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 21.6), Pair(Sex.F,  925.8)))
        asr.get(암종.유방암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 33.3), Pair(Sex.F,  586.0)))

        asr.get(암종.난소암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,   0.2)))
        asr.get(암종.난소암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,   1.8)))
        asr.get(암종.난소암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,   6.4)))
        asr.get(암종.난소암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  13.0)))
        asr.get(암종.난소암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  28.8)))
        asr.get(암종.난소암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  38.5)))
        asr.get(암종.난소암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  47.0)))
        asr.get(암종.난소암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  59.4)))
        asr.get(암종.난소암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  77.5)))
        asr.get(암종.난소암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 109.9)))
        asr.get(암종.난소암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 148.8)))
        asr.get(암종.난소암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 163.1)))
        asr.get(암종.난소암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 176.2)))
        asr.get(암종.난소암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 167.6)))
        asr.get(암종.난소암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 160.9)))
        asr.get(암종.난소암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 135.8)))
        asr.get(암종.난소암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  98.5)))
        asr.get(암종.난소암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  76.3)))

        asr.get(암종.기타암종)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,    56.3), Pair(Sex.F,    48.2)))
        asr.get(암종.기타암종)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,   120.9), Pair(Sex.F,   103.5)))
        asr.get(암종.기타암종)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,   160.1), Pair(Sex.F,   136.3)))
        asr.get(암종.기타암종)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,   203.8), Pair(Sex.F,   184.5)))
        asr.get(암종.기타암종)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,   234.0), Pair(Sex.F,   290.6)))
        asr.get(암종.기타암종)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,   308.4), Pair(Sex.F,   593.0)))
        asr.get(암종.기타암종)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   495.9), Pair(Sex.F,  1214.1)))
        asr.get(암종.기타암종)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   807.1), Pair(Sex.F,  2221.5)))
        asr.get(암종.기타암종)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,  1218.4), Pair(Sex.F,  3505.3)))
        asr.get(암종.기타암종)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  1761.0), Pair(Sex.F,  4938.4)))
        asr.get(암종.기타암종)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  2779.0), Pair(Sex.F,  6518.1)))
        asr.get(암종.기타암종)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  4473.3), Pair(Sex.F,  7787.1)))
        asr.get(암종.기타암종)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  7405.8), Pair(Sex.F,  8998.6)))
        asr.get(암종.기타암종)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 10933.0), Pair(Sex.F,  9339.1)))
        asr.get(암종.기타암종)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 15709.0), Pair(Sex.F, 10015.0)))
        asr.get(암종.기타암종)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 19148.0), Pair(Sex.F, 10019.0)))
        asr.get(암종.기타암종)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 22052.0), Pair(Sex.F, 10002.0)))
        asr.get(암종.기타암종)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 21703.0), Pair(Sex.F,  8585.7)))

        //endregion
    }
    enum class 암종 {
        폐암, 대장암, 간암, 췌장암, 식도암, 유방암, 난소암, 기타암종
    }
    enum class 결과 {
        GENERAL, CONCERN, RISK
    }
    fun findPPVbyAgeAndCancerAndSex(cancer: 암종, age: Int, sex: Sex): Double? {
        return ppv.get(cancer)?.get(age)?.get(sex)
    }
    fun findASRbyAgeAndCancerAndSex(cancer: 암종, age: Int, sex: Sex): Double? {
        return if(asr.get(cancer)?.get(age)?.get(sex)!! < 0.01) 0.01
        else asr.get(cancer)?.get(age)?.get(sex)
    }
}