package com.greencross.lims.report.avoid.repository

import com.google.common.collect.Range
import com.google.common.collect.TreeRangeMap
import com.greencross.lims.report.avoid.AvoidDto
import com.greencross.lims.report.builder.Sex
import org.springframework.stereotype.Repository
import java.util.*
import java.util.stream.Collectors

@Repository
class CancerRepo(
    private val ppv: Map<결과, Map<암종, TreeRangeMap<Int, Map<Sex, Double?>>>>,
    private val asr: Map<암종, TreeRangeMap<Int, Map<Sex, Double?>>>
) {
    constructor() : this(
        mapOf(*Arrays.stream(결과.values()).map{ it ->
            val maps = mapOf(*Arrays.stream(암종.values()).map { it2 ->
                val map: TreeRangeMap<Int, Map<Sex, Double?>> = TreeRangeMap.create()
                Pair(it2, map)
            }.collect(Collectors.toList()).toTypedArray())
            Pair(it, maps)
        }.collect(Collectors.toList()).toTypedArray()),
        mapOf(*Arrays.stream(암종.values()).map {
            val map: TreeRangeMap<Int, Map<Sex, Double?>> = TreeRangeMap.create()
            Pair(it, map)
        }.collect(Collectors.toList()).toTypedArray())
    ) {
        //region #ppv
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M,  0.00), Pair(Sex.F,  0.00)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M,  0.02), Pair(Sex.F,  0.04)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M,  0.08), Pair(Sex.F,  0.05)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M,  0.11), Pair(Sex.F,  0.10)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M,  0.17), Pair(Sex.F,  0.22)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M,  0.38), Pair(Sex.F,  0.44)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M,  0.79), Pair(Sex.F,  0.94)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M,  1.62), Pair(Sex.F,  1.82)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M,  3.45), Pair(Sex.F,  3.47)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M,  7.15), Pair(Sex.F,  6.16)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M, 13.88), Pair(Sex.F,  9.86)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, 22.68), Pair(Sex.F, 12.52)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, 30.56), Pair(Sex.F, 15.76)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, 34.96), Pair(Sex.F, 16.97)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(80,84), mapOf(Pair(Sex.M, 34.91), Pair(Sex.F, 16.10)))
        ppv[결과.CONCENT]?.get(암종.폐암)?.put(Range.closed(85,100),mapOf(Pair(Sex.M, 31.18), Pair(Sex.F, 12.85)))

        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M,  0.00), Pair(Sex.F,  0.00)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M,  0.00), Pair(Sex.F,  0.01)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M,  0.00), Pair(Sex.F,  0.01)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.02)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M,  0.03), Pair(Sex.F,  0.02)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M,  0.05), Pair(Sex.F,  0.04)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M,  0.08), Pair(Sex.F,  0.10)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M,  0.17), Pair(Sex.F,  0.19)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M,  0.35), Pair(Sex.F,  0.42)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M,  0.72), Pair(Sex.F,  0.81)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M,  1.55), Pair(Sex.F,  1.56)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M,  3.28), Pair(Sex.F,  2.81)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M,  6.62), Pair(Sex.F,  4.59)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, 11.43), Pair(Sex.F,  5.93)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, 16.23), Pair(Sex.F,  7.60)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, 19.12), Pair(Sex.F,  8.25)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(80,84), mapOf(Pair(Sex.M, 19.09), Pair(Sex.F,  7.79)))
        ppv[결과.ATTENTION]?.get(암종.폐암)?.put(Range.closed(85,100),mapOf(Pair(Sex.M, 16.62), Pair(Sex.F,  6.09)))

        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M,  0.00), Pair(Sex.F,  0.00)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M,  0.00), Pair(Sex.F,  0.00)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M,  0.03), Pair(Sex.F,  0.02)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M,  0.07), Pair(Sex.F,  0.06)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M,  0.13), Pair(Sex.F,  0.11)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M,  0.30), Pair(Sex.F,  0.28)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M,  0.75), Pair(Sex.F,  0.65)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M,  1.56), Pair(Sex.F,  1.39)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M,  2.81), Pair(Sex.F,  2.48)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M,  5.63), Pair(Sex.F,  4.73)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M,  9.84), Pair(Sex.F,  7.15)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M, 17.02), Pair(Sex.F, 10.96)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, 23.78), Pair(Sex.F, 14.50)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, 32.10), Pair(Sex.F, 19.38)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, 37.02), Pair(Sex.F, 23.23)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(80,84), mapOf(Pair(Sex.M, 41.53), Pair(Sex.F, 26.45)))
        ppv[결과.CONCENT]?.get(암종.대장암)?.put(Range.closed(85,100),mapOf(Pair(Sex.M, 43.47), Pair(Sex.F, 25.67)))

        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M,  0.00), Pair(Sex.F,  0.00)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M,  0.00), Pair(Sex.F,  0.00)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M,  0.00), Pair(Sex.F,  0.01)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M,  0.03), Pair(Sex.F,  0.03)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M,  0.06), Pair(Sex.F,  0.06)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M,  0.15), Pair(Sex.F,  0.14)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M,  0.38), Pair(Sex.F,  0.33)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M,  0.80), Pair(Sex.F,  0.71)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M,  1.45), Pair(Sex.F,  1.28)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M,  2.95), Pair(Sex.F,  2.47)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M,  5.27), Pair(Sex.F,  3.78)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M,  9.46), Pair(Sex.F,  5.90)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, 13.71), Pair(Sex.F,  7.95)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, 19.41), Pair(Sex.F, 10.91)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, 23.05), Pair(Sex.F, 13.35)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(80,84), mapOf(Pair(Sex.M, 26.57), Pair(Sex.F, 15.48)))
        ppv[결과.ATTENTION]?.get(암종.대장암)?.put(Range.closed(85,100),mapOf(Pair(Sex.M, 28.15), Pair(Sex.F, 14.96)))

        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M,  0.14), Pair(Sex.F,  0.10)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M,  0.22), Pair(Sex.F,  0.25)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M,  0.25), Pair(Sex.F,  0.18)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M,  0.17), Pair(Sex.F,  0.23)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M,  0.13), Pair(Sex.F,  0.11)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M,  0.15), Pair(Sex.F,  0.10)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M,  0.35), Pair(Sex.F,  0.20)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M,  1.21), Pair(Sex.F,  0.59)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M,  2.94), Pair(Sex.F,  0.97)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M,  6.65), Pair(Sex.F,  1.84)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 13.46), Pair(Sex.F,  3.36)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 21.36), Pair(Sex.F,  5.72)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 29.36), Pair(Sex.F,  9.30)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 33.20), Pair(Sex.F, 12.87)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 35.80), Pair(Sex.F, 15.45)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 34.41), Pair(Sex.F, 15.66)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 31.79), Pair(Sex.F, 13.57)))
        ppv[결과.CONCENT]?.get(암종.간암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 28.30), Pair(Sex.F, 10.17)))

        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M,  0.04), Pair(Sex.F,  0.03)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M,  0.06), Pair(Sex.F,  0.07)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M,  0.07), Pair(Sex.F,  0.05)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M,  0.05), Pair(Sex.F,  0.07)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M,  0.04), Pair(Sex.F,  0.03)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M,  0.04), Pair(Sex.F,  0.03)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M,  0.10), Pair(Sex.F,  0.06)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M,  0.36), Pair(Sex.F,  0.18)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M,  0.89), Pair(Sex.F,  0.29)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M,  2.08), Pair(Sex.F,  0.55)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M,  4.42), Pair(Sex.F,  1.02)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M,  7.48), Pair(Sex.F,  1.77)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 11.01), Pair(Sex.F,  2.96)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 12.88), Pair(Sex.F,  4.21)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 14.23), Pair(Sex.F,  5.16)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 13.50), Pair(Sex.F,  5.24)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 12.18), Pair(Sex.F,  4.46)))
        ppv[결과.ATTENTION]?.get(암종.간암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 10.51), Pair(Sex.F,  3.26)))

        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.00)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.02)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M, 0.03), Pair(Sex.F, 0.07)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M, 0.04), Pair(Sex.F, 0.12)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M, 0.04), Pair(Sex.F, 0.18)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M, 0.06), Pair(Sex.F, 0.24)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M, 0.11), Pair(Sex.F, 0.25)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M, 0.29), Pair(Sex.F, 0.41)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M, 0.48), Pair(Sex.F, 0.50)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M, 0.72), Pair(Sex.F, 0.71)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 1.41), Pair(Sex.F, 1.15)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 2.54), Pair(Sex.F, 1.87)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 4.02), Pair(Sex.F, 2.99)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 5.80), Pair(Sex.F, 3.98)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 7.20), Pair(Sex.F, 5.45)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 7.58), Pair(Sex.F, 5.95)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 7.12), Pair(Sex.F, 5.39)))
        ppv[결과.CONCENT]?.get(암종.췌장암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 6.99), Pair(Sex.F, 4.65)))

        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F, 0.00)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F, 0.01)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.02)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.04)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.06)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M, 0.02), Pair(Sex.F, 0.08)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M, 0.04), Pair(Sex.F, 0.08)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M, 0.09), Pair(Sex.F, 0.13)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M, 0.16), Pair(Sex.F, 0.16)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M, 0.23), Pair(Sex.F, 0.23)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 0.46), Pair(Sex.F, 0.38)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 0.84), Pair(Sex.F, 0.61)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 1.34), Pair(Sex.F, 0.99)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 1.96), Pair(Sex.F, 1.32)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 2.45), Pair(Sex.F, 1.83)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 2.59), Pair(Sex.F, 2.01)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 2.42), Pair(Sex.F, 1.81)))
        ppv[결과.ATTENTION]?.get(암종.췌장암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 2.37), Pair(Sex.F, 1.55)))

        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.01)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.00)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.00)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M,  0.03), Pair(Sex.F, 0.02)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M,  0.07), Pair(Sex.F, 0.07)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M,  0.29), Pair(Sex.F, 0.11)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M,  0.93), Pair(Sex.F, 0.22)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M,  2.47), Pair(Sex.F, 0.40)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M,  5.41), Pair(Sex.F, 0.64)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M,  9.22), Pair(Sex.F, 0.75)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 12.16), Pair(Sex.F, 0.87)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 14.40), Pair(Sex.F, 1.14)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 14.36), Pair(Sex.F, 1.22)))
        ppv[결과.CONCENT]?.get(암종.식도암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 10.98), Pair(Sex.F, 1.18)))

        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.01)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M,  0.02), Pair(Sex.F, 0.02)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M,  0.09), Pair(Sex.F, 0.03)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M,  0.29), Pair(Sex.F, 0.07)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M,  0.79), Pair(Sex.F, 0.13)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M,  1.76), Pair(Sex.F, 0.20)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M,  3.09), Pair(Sex.F, 0.24)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M,  4.16), Pair(Sex.F, 0.27)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M,  5.01), Pair(Sex.F, 0.36)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M,  5.00), Pair(Sex.F, 0.39)))
        ppv[결과.ATTENTION]?.get(암종.식도암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M,  3.72), Pair(Sex.F, 0.37)))

//        ppv.get(암종.유방암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.00)))
//        ppv.get(암종.유방암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.00)))
//        ppv.get(암종.유방암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.00)))
//        ppv.get(암종.유방암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.05)))
//        ppv.get(암종.유방암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.36)))
//        ppv.get(암종.유방암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.09)))
//        ppv.get(암종.유방암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M, 0.03), Pair(Sex.F,  8.97)))
//        ppv.get(암종.유방암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M, 0.03), Pair(Sex.F, 22.54)))
//        ppv.get(암종.유방암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M, 0.08), Pair(Sex.F, 40.53)))
//        ppv.get(암종.유방암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M, 0.16), Pair(Sex.F, 55.33)))
//        ppv.get(암종.유방암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 0.22), Pair(Sex.F, 62.86)))
//        ppv.get(암종.유방암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 0.49), Pair(Sex.F, 64.64)))
//        ppv.get(암종.유방암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 0.61), Pair(Sex.F, 65.21)))
//        ppv.get(암종.유방암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 0.91), Pair(Sex.F, 61.81)))
//        ppv.get(암종.유방암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 1.21), Pair(Sex.F, 58.59)))
//        ppv.get(암종.유방암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 1.47), Pair(Sex.F, 51.52)))
//        ppv.get(암종.유방암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 1.81), Pair(Sex.F, 44.33)))
//        ppv.get(암종.유방암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 2.76), Pair(Sex.F, 33.43)))

        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.01)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.07)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.23)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.47)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.04)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.39)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.69)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.12)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.75)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  3.86)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  5.16)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  5.63)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  6.05)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  5.77)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  5.55)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  4.73)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  3.47)))
        ppv[결과.CONCENT]?.get(암종.난소암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.71)))

        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.00)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.03)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.09)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.19)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.42)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.56)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.68)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.86)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.12)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.58)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.13)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.33)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.51)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.39)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.30)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.94)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.42)))
        ppv[결과.ATTENTION]?.get(암종.난소암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.10)))

        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(0,   4), mapOf(Pair(Sex.M,  2.74), Pair(Sex.F,  2.35)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(5,   9), mapOf(Pair(Sex.M,  5.70), Pair(Sex.F,  4.92)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,  7.41), Pair(Sex.F,  6.38)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,  9.25), Pair(Sex.F,  8.45)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M, 10.48), Pair(Sex.F, 12.70)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M, 13.38), Pair(Sex.F, 22.95)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M, 19.92), Pair(Sex.F, 38.03)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M, 28.89), Pair(Sex.F, 53.15)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M, 38.11), Pair(Sex.F, 64.46)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M, 47.23), Pair(Sex.F, 72.17)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M, 58.80), Pair(Sex.F, 77.68)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M, 70.04), Pair(Sex.F, 80.83)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M, 79.97), Pair(Sex.F, 83.16)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 85.97), Pair(Sex.F, 83.72)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 90.30), Pair(Sex.F, 84.75)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 92.20), Pair(Sex.F, 84.75)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 93.39), Pair(Sex.F, 84.73)))
        ppv[결과.CONCENT]?.get(암종.기타암종)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 93.26), Pair(Sex.F, 82.42)))

        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(0,   4), mapOf(Pair(Sex.M,  0.96), Pair(Sex.F,  0.82)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(5,   9), mapOf(Pair(Sex.M,  2.03), Pair(Sex.F,  1.75)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,  2.68), Pair(Sex.F,  2.29)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,  3.38), Pair(Sex.F,  3.07)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,  3.87), Pair(Sex.F,  4.76)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,  5.04), Pair(Sex.F,  9.28)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,  7.88), Pair(Sex.F,  17.41)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M, 12.25), Pair(Sex.F, 28.05)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M, 17.46), Pair(Sex.F, 38.39)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M, 23.52), Pair(Sex.F, 47.12)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M, 32.90), Pair(Sex.F, 54.47)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M, 44.55), Pair(Sex.F, 59.16)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M, 57.84), Pair(Sex.F, 62.91)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 67.80), Pair(Sex.F, 63.86)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 76.17), Pair(Sex.F, 65.63)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 80.25), Pair(Sex.F, 65.64)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 82.92), Pair(Sex.F, 65.60)))
        ppv[결과.ATTENTION]?.get(암종.기타암종)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 82.62), Pair(Sex.F, 61.70)))
        //endregion
        //region #asr
        asr.get(암종.폐암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,    0.1), Pair(Sex.F,   0.1)))
        asr.get(암종.폐암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,    0.2), Pair(Sex.F,   0.4)))
        asr.get(암종.폐암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,    0.2), Pair(Sex.F,   0.4)))
        asr.get(암종.폐암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,    0.5), Pair(Sex.F,   1.1)))
        asr.get(암종.폐암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,    2.3), Pair(Sex.F,   1.4)))
        asr.get(암종.폐암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,    3.3), Pair(Sex.F,   3.0)))
        asr.get(암종.폐암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,    5.2), Pair(Sex.F,   6.8)))
        asr.get(암종.폐암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   11.7), Pair(Sex.F,  13.3)))
        asr.get(암종.폐암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   24.1), Pair(Sex.F,  28.7)))
        asr.get(암종.폐암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,   49.8), Pair(Sex.F,  56.2)))
        asr.get(암종.폐암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  108.1), Pair(Sex.F, 108.7)))
        asr.get(암종.폐암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  232.8), Pair(Sex.F, 198.4)))
        asr.get(암종.폐암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  485.7), Pair(Sex.F, 330.3)))
        asr.get(암종.폐암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M,  880.6), Pair(Sex.F, 431.7)))
        asr.get(암종.폐암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 1315.5), Pair(Sex.F, 563.3)))
        asr.get(암종.폐암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 1601.4), Pair(Sex.F, 615.1)))
        asr.get(암종.폐암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 1598.4), Pair(Sex.F, 577.7)))
        asr.get(암종.폐암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 1353.7), Pair(Sex.F, 444.5)))

        asr.get(암종.대장암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,    0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.대장암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,    0.1), Pair(Sex.F,    0.1)))
        asr.get(암종.대장암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,    0.2), Pair(Sex.F,    0.4)))
        asr.get(암종.대장암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,    1.0), Pair(Sex.F,    0.7)))
        asr.get(암종.대장암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,    2.4), Pair(Sex.F,    2.3)))
        asr.get(암종.대장암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,    4.6), Pair(Sex.F,    4.0)))
        asr.get(암종.대장암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   11.1), Pair(Sex.F,   10.2)))
        asr.get(암종.대장암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   27.6), Pair(Sex.F,   23.9)))
        asr.get(암종.대장암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   57.9), Pair(Sex.F,   51.3)))
        asr.get(암종.대장암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  105.5), Pair(Sex.F,   92.7)))
        asr.get(암종.대장암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  217.3), Pair(Sex.F,  181.2)))
        asr.get(암종.대장암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  397.1), Pair(Sex.F,  280.6)))
        asr.get(암종.대장암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  744.0), Pair(Sex.F,  447.8)))
        asr.get(암종.대장암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 1127.0), Pair(Sex.F,  615.9)))
        asr.get(암종.대장암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 1697.7), Pair(Sex.F,  870.8)))
        asr.get(암종.대장암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 2102.7), Pair(Sex.F, 1093.1)))
        asr.get(암종.대장암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 2529.6), Pair(Sex.F, 1297.0)))
        asr.get(암종.대장암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 2732.6), Pair(Sex.F, 1245.7)))

        asr.get(암종.간암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M,   2.2), Pair(Sex.F,   1.6)))
        asr.get(암종.간암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M,   3.4), Pair(Sex.F,   3.9)))
        asr.get(암종.간암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M,   3.9), Pair(Sex.F,   2.8)))
        asr.get(암종.간암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M,   2.7), Pair(Sex.F,   3.6)))
        asr.get(암종.간암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M,   2.1), Pair(Sex.F,   1.7)))
        asr.get(암종.간암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M,   2.3), Pair(Sex.F,   1.6)))
        asr.get(암종.간암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M,   5.5), Pair(Sex.F,   3.1)))
        asr.get(암종.간암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M,  19.1), Pair(Sex.F,   9.3)))
        asr.get(암종.간암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M,  47.2), Pair(Sex.F,  15.3)))
        asr.get(암종.간암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M, 111.0), Pair(Sex.F,  29.2)))
        asr.get(암종.간암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M, 241.8), Pair(Sex.F,  54.2)))
        asr.get(암종.간암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M, 421.7), Pair(Sex.F,  94.5)))
        asr.get(암종.간암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M, 643.9), Pair(Sex.F, 159.5)))
        asr.get(암종.간암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, 768.8), Pair(Sex.F, 229.7)))
        asr.get(암종.간암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, 861.7), Pair(Sex.F, 284.0)))
        asr.get(암종.간암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, 811.3), Pair(Sex.F, 288.6)))
        asr.get(암종.간암)?.put(Range.closed(80,84), mapOf(Pair(Sex.M, 721.2), Pair(Sex.F, 244.2)))
        asr.get(암종.간암)?.put(Range.closed(85,89), mapOf(Pair(Sex.M, 611.7), Pair(Sex.F, 176.2)))

        asr.get(암종.췌장암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,   0.1), Pair(Sex.F,   0.0)))
        asr.get(암종.췌장암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,   0.2), Pair(Sex.F,   0.3)))
        asr.get(암종.췌장암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,   0.5), Pair(Sex.F,   1.2)))
        asr.get(암종.췌장암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,   0.7), Pair(Sex.F,   2.0)))
        asr.get(암종.췌장암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,   0.7), Pair(Sex.F,   3.0)))
        asr.get(암종.췌장암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,   1.0), Pair(Sex.F,   4.0)))
        asr.get(암종.췌장암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   1.8), Pair(Sex.F,   4.1)))
        asr.get(암종.췌장암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   4.8), Pair(Sex.F,   6.7)))
        asr.get(암종.췌장암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   7.9), Pair(Sex.F,   8.3)))
        asr.get(암종.췌장암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  11.9), Pair(Sex.F,  11.7)))
        asr.get(암종.췌장암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  23.5), Pair(Sex.F,  19.2)))
        asr.get(암종.췌장암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  42.9), Pair(Sex.F,  31.3)))
        asr.get(암종.췌장암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  68.8), Pair(Sex.F,  50.7)))
        asr.get(암종.췌장암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 101.2), Pair(Sex.F,  68.1)))
        asr.get(암종.췌장암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 127.4), Pair(Sex.F,  94.6)))
        asr.get(암종.췌장암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 134.7), Pair(Sex.F, 103.9)))
        asr.get(암종.췌장암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 125.8), Pair(Sex.F,  93.6)))
        asr.get(암종.췌장암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 123.4), Pair(Sex.F,  80.1)))

        asr.get(암종.식도암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.1)))
        asr.get(암종.식도암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,   0.2), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   0.1), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   0.5), Pair(Sex.F,  0.4)))
        asr.get(암종.식도암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   1.1), Pair(Sex.F,  1.2)))
        asr.get(암종.식도암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,   4.8), Pair(Sex.F,  1.8)))
        asr.get(암종.식도암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  15.7), Pair(Sex.F,  3.7)))
        asr.get(암종.식도암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  42.5), Pair(Sex.F,  6.7)))
        asr.get(암종.식도암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  95.9), Pair(Sex.F, 10.8)))
        asr.get(암종.식도암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 170.0), Pair(Sex.F, 12.7)))
        asr.get(암종.식도암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 231.7), Pair(Sex.F, 14.7)))
        asr.get(암종.식도암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 281.3), Pair(Sex.F, 19.3)))
        asr.get(암종.식도암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 280.4), Pair(Sex.F, 20.7)))
        asr.get(암종.식도암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 206.4), Pair(Sex.F, 20.1)))

        asr.get(암종.유방암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.유방암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.유방암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.유방암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.6)))
        asr.get(암종.유방암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    4.2)))
        asr.get(암종.유방암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,   25.1)))
        asr.get(암종.유방암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,  0.3), Pair(Sex.F,  115.5)))
        asr.get(암종.유방암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,  0.4), Pair(Sex.F,  340.3)))
        asr.get(암종.유방암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,  0.9), Pair(Sex.F,  793.7)))
        asr.get(암종.유방암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  1.9), Pair(Sex.F, 1433.1)))
        asr.get(암종.유방암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  2.6), Pair(Sex.F, 1948.1)))
        asr.get(암종.유방암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  5.8), Pair(Sex.F, 2100.8)))
        asr.get(암종.유방암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  7.2), Pair(Sex.F, 2152.2)))
        asr.get(암종.유방암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 10.8), Pair(Sex.F, 1864.2)))
        asr.get(암종.유방암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 14.4), Pair(Sex.F, 1633.5)))
        asr.get(암종.유방암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 17.5), Pair(Sex.F, 1231.9)))
        asr.get(암종.유방암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 21.6), Pair(Sex.F,  925.8)))
        asr.get(암종.유방암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 33.3), Pair(Sex.F,  586.0)))

        asr.get(암종.난소암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,   0.2)))
        asr.get(암종.난소암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,   1.8)))
        asr.get(암종.난소암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,   6.4)))
        asr.get(암종.난소암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  13.0)))
        asr.get(암종.난소암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  28.8)))
        asr.get(암종.난소암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  38.5)))
        asr.get(암종.난소암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  47.0)))
        asr.get(암종.난소암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  59.4)))
        asr.get(암종.난소암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  77.5)))
        asr.get(암종.난소암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 109.9)))
        asr.get(암종.난소암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 148.8)))
        asr.get(암종.난소암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 163.1)))
        asr.get(암종.난소암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 176.2)))
        asr.get(암종.난소암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 167.6)))
        asr.get(암종.난소암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 160.9)))
        asr.get(암종.난소암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 135.8)))
        asr.get(암종.난소암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  98.5)))
        asr.get(암종.난소암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  76.3)))

        asr.get(암종.기타암종)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,    56.3), Pair(Sex.F,    48.2)))
        asr.get(암종.기타암종)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,   120.9), Pair(Sex.F,   103.5)))
        asr.get(암종.기타암종)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,   160.1), Pair(Sex.F,   136.3)))
        asr.get(암종.기타암종)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,   203.8), Pair(Sex.F,   184.5)))
        asr.get(암종.기타암종)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,   234.0), Pair(Sex.F,   290.6)))
        asr.get(암종.기타암종)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,   308.4), Pair(Sex.F,   593.0)))
        asr.get(암종.기타암종)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   495.9), Pair(Sex.F,  1214.1)))
        asr.get(암종.기타암종)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   807.1), Pair(Sex.F,  2221.5)))
        asr.get(암종.기타암종)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,  1218.4), Pair(Sex.F,  3505.3)))
        asr.get(암종.기타암종)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  1761.0), Pair(Sex.F,  4938.4)))
        asr.get(암종.기타암종)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  2779.0), Pair(Sex.F,  6518.1)))
        asr.get(암종.기타암종)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  4473.3), Pair(Sex.F,  7787.1)))
        asr.get(암종.기타암종)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  7405.8), Pair(Sex.F,  8998.6)))
        asr.get(암종.기타암종)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 10933.0), Pair(Sex.F,  9339.1)))
        asr.get(암종.기타암종)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 15709.0), Pair(Sex.F, 10015.0)))
        asr.get(암종.기타암종)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 19148.0), Pair(Sex.F, 10019.0)))
        asr.get(암종.기타암종)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 22052.0), Pair(Sex.F, 10002.0)))
        asr.get(암종.기타암종)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 21703.0), Pair(Sex.F,  8585.7)))

        //endregion
    }
    enum class 암종 {
        폐암, 대장암, 간암, 췌장암, 식도암, 유방암, 난소암, 기타암종
    }
    enum class 결과 {
        ATTENTION, CONCENT
    }
    fun findPPVbyAgeAndCancerAndSex(result: 결과, cancer: 암종, age: Int, sex: Sex): Double? {
        return ppv.get(result)?.get(cancer)?.get(age)?.get(sex)
    }
    fun findASRbyAgeAndCancerAndSex(cancer: 암종, age: Int, sex: Sex): Double? {
        return asr.get(cancer)?.get(age)?.get(sex)
    }
}