package com.greencross.lims.report.avoid.repository

import com.google.common.collect.Range
import com.google.common.collect.TreeRangeMap
import com.greencross.lims.report.avoid.AvoidResource
import com.greencross.lims.report.avoid.AvoidTemplate
import com.greencross.lims.report.builder.Sex
import java.util.*
import java.util.stream.Collectors

abstract class CancerRepo(
    private val ppv: Map<암종, TreeRangeMap<Int, Map<Sex, Double?>>>,
    private val asr: Map<암종, TreeRangeMap<Int, Map<Sex, Double?>>>
) : AvoidTemplate<AvoidResource>{
    constructor() : this(
        mapOf(*Arrays.stream(암종.values()).map {
            val map: TreeRangeMap<Int, Map<Sex, Double?>> = TreeRangeMap.create()
            Pair(it, map)
        }.collect(Collectors.toList()).toTypedArray()),
        mapOf(*Arrays.stream(암종.values()).map {
            val map: TreeRangeMap<Int, Map<Sex, Double?>> = TreeRangeMap.create()
            Pair(it, map)
        }.collect(Collectors.toList()).toTypedArray())
    ) {
        //region #ppv
        ppv.get(암종.폐암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.01)))
        ppv.get(암종.폐암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.03)))
        ppv.get(암종.폐암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M,  0.01), Pair(Sex.F,  0.03)))
        ppv.get(암종.폐암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M,  0.04), Pair(Sex.F,  0.08)))
        ppv.get(암종.폐암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M,  0.17), Pair(Sex.F,  0.10)))
        ppv.get(암종.폐암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M,  0.24), Pair(Sex.F,  0.22)))
        ppv.get(암종.폐암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M,  0.38), Pair(Sex.F,  0.49)))
        ppv.get(암종.폐암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M,  0.85), Pair(Sex.F,  0.96)))
        ppv.get(암종.폐암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M,  1.73), Pair(Sex.F,  2.06)))
        ppv.get(암종.폐암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M,  3.51), Pair(Sex.F,  3.95)))
        ppv.get(암종.폐암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M,  7.33), Pair(Sex.F,  7.37)))
        ppv.get(암종.폐암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M, 14.57), Pair(Sex.F, 12.69)))
        ppv.get(암종.폐암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M, 26.30), Pair(Sex.F, 19.50)))
        ppv.get(암종.폐암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, 39.37), Pair(Sex.F, 24.07)))
        ppv.get(암종.폐암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, 49.35), Pair(Sex.F, 29.28)))
        ppv.get(암종.폐암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, 54.33), Pair(Sex.F, 31.15)))
        ppv.get(암종.폐암)?.put(Range.closed(80,59), mapOf(Pair(Sex.M, 54.28), Pair(Sex.F, 29.81)))
        ppv.get(암종.폐암)?.put(Range.closed(85,100),mapOf(Pair(Sex.M, 50.08), Pair(Sex.F, 24.61)))

        ppv.get(암종.대장암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(80,59), mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))
        ppv.get(암종.대장암)?.put(Range.closed(85,100),mapOf(Pair(Sex.M, null), Pair(Sex.F, null)))

        ppv.get(암종.간암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M,  0.21), Pair(Sex.F,  0.16)))
        ppv.get(암종.간암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M,  0.33), Pair(Sex.F,  0.38)))
        ppv.get(암종.간암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M,  0.38), Pair(Sex.F,  0.27)))
        ppv.get(암종.간암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M,  0.26), Pair(Sex.F,  0.35)))
        ppv.get(암종.간암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M,  0.20), Pair(Sex.F,  0.17)))
        ppv.get(암종.간암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M,  0.22), Pair(Sex.F,  0.16)))
        ppv.get(암종.간암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M,  0.54), Pair(Sex.F,  0.30)))
        ppv.get(암종.간암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M,  1.83), Pair(Sex.F,  0.90)))
        ppv.get(암종.간암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M,  4.41), Pair(Sex.F,  1.47)))
        ppv.get(암종.간암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M,  9.80), Pair(Sex.F,  2.78)))
        ppv.get(암종.간암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 19.16), Pair(Sex.F,  5.04)))
        ppv.get(암종.간암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 29.29), Pair(Sex.F,  8.47)))
        ppv.get(암종.간암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 38.79), Pair(Sex.F, 13.51)))
        ppv.get(암종.간암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 43.11), Pair(Sex.F, 18.38)))
        ppv.get(암종.간암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 45.94), Pair(Sex.F, 21.79)))
        ppv.get(암종.간암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 44.44), Pair(Sex.F, 22.06)))
        ppv.get(암종.간암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 41.54), Pair(Sex.F, 19.32)))
        ppv.get(암종.간암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 37.58), Pair(Sex.F, 14.72)))

        ppv.get(암종.췌장암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M, 0.01), Pair(Sex.F, 0.00)))
        ppv.get(암종.췌장암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M, 0.02), Pair(Sex.F, 0.02)))
        ppv.get(암종.췌장암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M, 0.04), Pair(Sex.F, 0.09)))
        ppv.get(암종.췌장암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M, 0.05), Pair(Sex.F, 0.15)))
        ppv.get(암종.췌장암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M, 0.05), Pair(Sex.F, 0.23)))
        ppv.get(암종.췌장암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M, 0.08), Pair(Sex.F, 0.31)))
        ppv.get(암종.췌장암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M, 0.14), Pair(Sex.F, 0.31)))
        ppv.get(암종.췌장암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M, 0.37), Pair(Sex.F, 0.51)))
        ppv.get(암종.췌장암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M, 0.60), Pair(Sex.F, 0.63)))
        ppv.get(암종.췌장암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M, 0.90), Pair(Sex.F, 0.89)))
        ppv.get(암종.췌장암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 1.77), Pair(Sex.F, 1.45)))
        ppv.get(암종.췌장암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 3.18), Pair(Sex.F, 2.34)))
        ppv.get(암종.췌장암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 5.00), Pair(Sex.F, 3.74)))
        ppv.get(암종.췌장암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 7.19), Pair(Sex.F, 4.95)))
        ppv.get(암종.췌장암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 8.89), Pair(Sex.F, 6.75)))
        ppv.get(암종.췌장암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 9.35), Pair(Sex.F, 7.37)))
        ppv.get(암종.췌장암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 8.79), Pair(Sex.F, 6.69)))
        ppv.get(암종.췌장암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 8.64), Pair(Sex.F, 5.78)))

        ppv.get(암종.식도암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv.get(암종.식도암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.01)))
        ppv.get(암종.식도암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv.get(암종.식도암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv.get(암종.식도암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M,  0.00), Pair(Sex.F, 0.00)))
        ppv.get(암종.식도암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.00)))
        ppv.get(암종.식도암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M,  0.01), Pair(Sex.F, 0.00)))
        ppv.get(암종.식도암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M,  0.03), Pair(Sex.F, 0.03)))
        ppv.get(암종.식도암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M,  0.07), Pair(Sex.F, 0.08)))
        ppv.get(암종.식도암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M,  0.32), Pair(Sex.F, 0.12)))
        ppv.get(암종.식도암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M,  1.04), Pair(Sex.F, 0.25)))
        ppv.get(암종.식도암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M,  2.76), Pair(Sex.F, 0.44)))
        ppv.get(암종.식도암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M,  6.02), Pair(Sex.F, 0.72)))
        ppv.get(암종.식도암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 10.20), Pair(Sex.F, 0.84)))
        ppv.get(암종.식도암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 13.41), Pair(Sex.F, 0.97)))
        ppv.get(암종.식도암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 15.84), Pair(Sex.F, 1.27)))
        ppv.get(암종.식도암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 15.79), Pair(Sex.F, 1.36)))
        ppv.get(암종.식도암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 12.12), Pair(Sex.F, 1.32)))

        ppv.get(암종.유방암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.00)))
        ppv.get(암종.유방암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.00)))
        ppv.get(암종.유방암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.00)))
        ppv.get(암종.유방암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.05)))
        ppv.get(암종.유방암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.36)))
        ppv.get(암종.유방암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.09)))
        ppv.get(암종.유방암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M, 0.03), Pair(Sex.F,  8.97)))
        ppv.get(암종.유방암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M, 0.03), Pair(Sex.F, 22.54)))
        ppv.get(암종.유방암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M, 0.08), Pair(Sex.F, 40.53)))
        ppv.get(암종.유방암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M, 0.16), Pair(Sex.F, 55.33)))
        ppv.get(암종.유방암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 0.22), Pair(Sex.F, 62.86)))
        ppv.get(암종.유방암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 0.49), Pair(Sex.F, 64.64)))
        ppv.get(암종.유방암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 0.61), Pair(Sex.F, 65.21)))
        ppv.get(암종.유방암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 0.91), Pair(Sex.F, 61.81)))
        ppv.get(암종.유방암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 1.21), Pair(Sex.F, 58.59)))
        ppv.get(암종.유방암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 1.47), Pair(Sex.F, 51.52)))
        ppv.get(암종.유방암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 1.81), Pair(Sex.F, 44.33)))
        ppv.get(암종.유방암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 2.76), Pair(Sex.F, 33.43)))

        ppv.get(암종.난소암)?.put(Range.closed( 0, 4),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.02)))
        ppv.get(암종.난소암)?.put(Range.closed( 5, 9),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.15)))
        ppv.get(암종.난소암)?.put(Range.closed(10,14),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  0.53)))
        ppv.get(암종.난소암)?.put(Range.closed(15,19),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  1.07)))
        ppv.get(암종.난소암)?.put(Range.closed(20,24),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  2.34)))
        ppv.get(암종.난소암)?.put(Range.closed(25,29),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  3.11)))
        ppv.get(암종.난소암)?.put(Range.closed(30,34),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  3.77)))
        ppv.get(암종.난소암)?.put(Range.closed(35,39),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  4.72)))
        ppv.get(암종.난소암)?.put(Range.closed(40,44),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  6.07)))
        ppv.get(암종.난소암)?.put(Range.closed(45,49),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  8.40)))
        ppv.get(암종.난소암)?.put(Range.closed(50,54),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F, 11.04)))
        ppv.get(암종.난소암)?.put(Range.closed(55,59),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F, 11.98)))
        ppv.get(암종.난소암)?.put(Range.closed(60,64),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F, 12.82)))
        ppv.get(암종.난소암)?.put(Range.closed(65,69),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F, 12.27)))
        ppv.get(암종.난소암)?.put(Range.closed(70,74),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F, 11.84)))
        ppv.get(암종.난소암)?.put(Range.closed(75,79),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F, 10.17)))
        ppv.get(암종.난소암)?.put(Range.closed(80,84),  mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  7.59)))
        ppv.get(암종.난소암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 0.00), Pair(Sex.F,  5.98)))

        ppv.get(암종.모든암)?.put(Range.closed(0,   4), mapOf(Pair(Sex.M,  4.55), Pair(Sex.F,  3.92)))
        ppv.get(암종.모든암)?.put(Range.closed(5,   9), mapOf(Pair(Sex.M,  9.29), Pair(Sex.F,  8.06)))
        ppv.get(암종.모든암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M, 11.95), Pair(Sex.F, 10.35)))
        ppv.get(암종.모든암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M, 14.73), Pair(Sex.F, 13.52)))
        ppv.get(암종.모든암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M, 16.56), Pair(Sex.F, 19.78)))
        ppv.get(암종.모든암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M, 20.74), Pair(Sex.F, 33.54)))
        ppv.get(암종.모든암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M, 29.66), Pair(Sex.F, 50.97)))
        ppv.get(암종.모든암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M, 40.77), Pair(Sex.F, 65.78)))
        ppv.get(암종.모든암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M, 51.06), Pair(Sex.F, 75.45)))
        ppv.get(암종.모든암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M, 60.26), Pair(Sex.F, 81.46)))
        ppv.get(암종.모든암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M, 70.75), Pair(Sex.F, 85.50)))
        ppv.get(암종.모든암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M, 79.85), Pair(Sex.F, 87.72)))
        ppv.get(암종.모든암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M, 87.12), Pair(Sex.F, 89.32)))
        ppv.get(암종.모든암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 91.22), Pair(Sex.F, 89.71)))
        ppv.get(암종.모든암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 94.04), Pair(Sex.F, 90.40)))
        ppv.get(암종.모든암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 95.25), Pair(Sex.F, 90.40)))
        ppv.get(암종.모든암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 95.99), Pair(Sex.F, 90.39)))
        ppv.get(암종.모든암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 95.91), Pair(Sex.F, 88.82)))
        //endregion
        //region #asr
        asr.get(암종.폐암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,    0.1), Pair(Sex.F,   0.1)))
        asr.get(암종.폐암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,    0.2), Pair(Sex.F,   0.4)))
        asr.get(암종.폐암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,    0.2), Pair(Sex.F,   0.4)))
        asr.get(암종.폐암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,    0.5), Pair(Sex.F,   1.1)))
        asr.get(암종.폐암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,    2.3), Pair(Sex.F,   1.4)))
        asr.get(암종.폐암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,    3.3), Pair(Sex.F,   3.0)))
        asr.get(암종.폐암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,    5.2), Pair(Sex.F,   6.8)))
        asr.get(암종.폐암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   11.7), Pair(Sex.F,  13.3)))
        asr.get(암종.폐암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   24.1), Pair(Sex.F,  28.7)))
        asr.get(암종.폐암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,   49.8), Pair(Sex.F,  56.2)))
        asr.get(암종.폐암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  108.1), Pair(Sex.F, 108.7)))
        asr.get(암종.폐암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  232.8), Pair(Sex.F, 198.4)))
        asr.get(암종.폐암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  485.7), Pair(Sex.F, 330.3)))
        asr.get(암종.폐암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M,  880.6), Pair(Sex.F, 431.7)))
        asr.get(암종.폐암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 1315.5), Pair(Sex.F, 563.3)))
        asr.get(암종.폐암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 1601.4), Pair(Sex.F, 615.1)))
        asr.get(암종.폐암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 1598.4), Pair(Sex.F, 577.7)))
        asr.get(암종.폐암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 1353.7), Pair(Sex.F, 444.5)))

        asr.get(암종.대장암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,    0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.대장암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,    0.1), Pair(Sex.F,    0.1)))
        asr.get(암종.대장암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,    0.2), Pair(Sex.F,    0.4)))
        asr.get(암종.대장암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,    1.0), Pair(Sex.F,    0.7)))
        asr.get(암종.대장암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,    2.4), Pair(Sex.F,    2.3)))
        asr.get(암종.대장암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,    4.6), Pair(Sex.F,    4.0)))
        asr.get(암종.대장암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   11.1), Pair(Sex.F,   10.2)))
        asr.get(암종.대장암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   27.6), Pair(Sex.F,   23.9)))
        asr.get(암종.대장암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   57.9), Pair(Sex.F,   51.3)))
        asr.get(암종.대장암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  105.5), Pair(Sex.F,   92.7)))
        asr.get(암종.대장암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  217.3), Pair(Sex.F,  181.2)))
        asr.get(암종.대장암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  397.1), Pair(Sex.F,  280.6)))
        asr.get(암종.대장암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  744.0), Pair(Sex.F,  447.8)))
        asr.get(암종.대장암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 1127.0), Pair(Sex.F,  615.9)))
        asr.get(암종.대장암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 1697.7), Pair(Sex.F,  870.8)))
        asr.get(암종.대장암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 2102.7), Pair(Sex.F, 1093.1)))
        asr.get(암종.대장암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 2529.6), Pair(Sex.F, 1297.0)))
        asr.get(암종.대장암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 2732.6), Pair(Sex.F, 1245.7)))

        asr.get(암종.간암)?.put(Range.closed( 0, 4), mapOf(Pair(Sex.M,   2.2), Pair(Sex.F,   1.6)))
        asr.get(암종.간암)?.put(Range.closed( 5, 9), mapOf(Pair(Sex.M,   3.4), Pair(Sex.F,   3.9)))
        asr.get(암종.간암)?.put(Range.closed(10,14), mapOf(Pair(Sex.M,   3.9), Pair(Sex.F,   2.8)))
        asr.get(암종.간암)?.put(Range.closed(15,19), mapOf(Pair(Sex.M,   2.7), Pair(Sex.F,   3.6)))
        asr.get(암종.간암)?.put(Range.closed(20,24), mapOf(Pair(Sex.M,   2.1), Pair(Sex.F,   1.7)))
        asr.get(암종.간암)?.put(Range.closed(25,29), mapOf(Pair(Sex.M,   2.3), Pair(Sex.F,   1.6)))
        asr.get(암종.간암)?.put(Range.closed(30,34), mapOf(Pair(Sex.M,   5.5), Pair(Sex.F,   3.1)))
        asr.get(암종.간암)?.put(Range.closed(35,39), mapOf(Pair(Sex.M,  19.1), Pair(Sex.F,   9.3)))
        asr.get(암종.간암)?.put(Range.closed(40,44), mapOf(Pair(Sex.M,  47.2), Pair(Sex.F,  15.3)))
        asr.get(암종.간암)?.put(Range.closed(45,49), mapOf(Pair(Sex.M, 111.0), Pair(Sex.F,  29.2)))
        asr.get(암종.간암)?.put(Range.closed(50,54), mapOf(Pair(Sex.M, 241.8), Pair(Sex.F,  54.2)))
        asr.get(암종.간암)?.put(Range.closed(55,59), mapOf(Pair(Sex.M, 421.7), Pair(Sex.F,  94.5)))
        asr.get(암종.간암)?.put(Range.closed(60,64), mapOf(Pair(Sex.M, 643.9), Pair(Sex.F, 159.5)))
        asr.get(암종.간암)?.put(Range.closed(65,69), mapOf(Pair(Sex.M, 768.8), Pair(Sex.F, 229.7)))
        asr.get(암종.간암)?.put(Range.closed(70,74), mapOf(Pair(Sex.M, 861.7), Pair(Sex.F, 284.0)))
        asr.get(암종.간암)?.put(Range.closed(75,79), mapOf(Pair(Sex.M, 811.3), Pair(Sex.F, 288.6)))
        asr.get(암종.간암)?.put(Range.closed(80,84), mapOf(Pair(Sex.M, 721.2), Pair(Sex.F, 244.2)))
        asr.get(암종.간암)?.put(Range.closed(85,89), mapOf(Pair(Sex.M, 611.7), Pair(Sex.F, 176.2)))

        asr.get(암종.췌장암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,   0.1), Pair(Sex.F,   0.0)))
        asr.get(암종.췌장암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,   0.2), Pair(Sex.F,   0.3)))
        asr.get(암종.췌장암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,   0.5), Pair(Sex.F,   1.2)))
        asr.get(암종.췌장암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,   0.7), Pair(Sex.F,   2.0)))
        asr.get(암종.췌장암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,   0.7), Pair(Sex.F,   3.0)))
        asr.get(암종.췌장암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,   1.0), Pair(Sex.F,   4.0)))
        asr.get(암종.췌장암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   1.8), Pair(Sex.F,   4.1)))
        asr.get(암종.췌장암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   4.8), Pair(Sex.F,   6.7)))
        asr.get(암종.췌장암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   7.9), Pair(Sex.F,   8.3)))
        asr.get(암종.췌장암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  11.9), Pair(Sex.F,  11.7)))
        asr.get(암종.췌장암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  23.5), Pair(Sex.F,  19.2)))
        asr.get(암종.췌장암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  42.9), Pair(Sex.F,  31.3)))
        asr.get(암종.췌장암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  68.8), Pair(Sex.F,  50.7)))
        asr.get(암종.췌장암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 101.2), Pair(Sex.F,  68.1)))
        asr.get(암종.췌장암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 127.4), Pair(Sex.F,  94.6)))
        asr.get(암종.췌장암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 134.7), Pair(Sex.F, 103.9)))
        asr.get(암종.췌장암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 125.8), Pair(Sex.F,  93.6)))
        asr.get(암종.췌장암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 123.4), Pair(Sex.F,  80.1)))

        asr.get(암종.식도암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.1)))
        asr.get(암종.식도암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,   0.0), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,   0.2), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   0.1), Pair(Sex.F,  0.0)))
        asr.get(암종.식도암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   0.5), Pair(Sex.F,  0.4)))
        asr.get(암종.식도암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,   1.1), Pair(Sex.F,  1.2)))
        asr.get(암종.식도암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,   4.8), Pair(Sex.F,  1.8)))
        asr.get(암종.식도암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  15.7), Pair(Sex.F,  3.7)))
        asr.get(암종.식도암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  42.5), Pair(Sex.F,  6.7)))
        asr.get(암종.식도암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  95.9), Pair(Sex.F, 10.8)))
        asr.get(암종.식도암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 170.0), Pair(Sex.F, 12.7)))
        asr.get(암종.식도암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 231.7), Pair(Sex.F, 14.7)))
        asr.get(암종.식도암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 281.3), Pair(Sex.F, 19.3)))
        asr.get(암종.식도암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 280.4), Pair(Sex.F, 20.7)))
        asr.get(암종.식도암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 206.4), Pair(Sex.F, 20.1)))

        asr.get(암종.유방암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.유방암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.유방암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.0)))
        asr.get(암종.유방암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    0.6)))
        asr.get(암종.유방암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,    4.2)))
        asr.get(암종.유방암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,  0.0), Pair(Sex.F,   25.1)))
        asr.get(암종.유방암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,  0.3), Pair(Sex.F,  115.5)))
        asr.get(암종.유방암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,  0.4), Pair(Sex.F,  340.3)))
        asr.get(암종.유방암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,  0.9), Pair(Sex.F,  793.7)))
        asr.get(암종.유방암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  1.9), Pair(Sex.F, 1433.1)))
        asr.get(암종.유방암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  2.6), Pair(Sex.F, 1948.1)))
        asr.get(암종.유방암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  5.8), Pair(Sex.F, 2100.8)))
        asr.get(암종.유방암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  7.2), Pair(Sex.F, 2152.2)))
        asr.get(암종.유방암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 10.8), Pair(Sex.F, 1864.2)))
        asr.get(암종.유방암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 14.4), Pair(Sex.F, 1633.5)))
        asr.get(암종.유방암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 17.5), Pair(Sex.F, 1231.9)))
        asr.get(암종.유방암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 21.6), Pair(Sex.F,  925.8)))
        asr.get(암종.유방암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 33.3), Pair(Sex.F,  586.0)))

        asr.get(암종.난소암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,   0.2)))
        asr.get(암종.난소암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,   1.8)))
        asr.get(암종.난소암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,   6.4)))
        asr.get(암종.난소암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  13.0)))
        asr.get(암종.난소암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  28.8)))
        asr.get(암종.난소암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  38.5)))
        asr.get(암종.난소암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  47.0)))
        asr.get(암종.난소암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  59.4)))
        asr.get(암종.난소암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  77.5)))
        asr.get(암종.난소암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 109.9)))
        asr.get(암종.난소암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 148.8)))
        asr.get(암종.난소암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 163.1)))
        asr.get(암종.난소암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 176.2)))
        asr.get(암종.난소암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 167.6)))
        asr.get(암종.난소암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 160.9)))
        asr.get(암종.난소암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F, 135.8)))
        asr.get(암종.난소암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  98.5)))
        asr.get(암종.난소암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 0.0), Pair(Sex.F,  76.3)))

        asr.get(암종.모든암)?.put(Range.closed( 0,  4), mapOf(Pair(Sex.M,    56.3), Pair(Sex.F,    48.2)))
        asr.get(암종.모든암)?.put(Range.closed( 5,  9), mapOf(Pair(Sex.M,   120.9), Pair(Sex.F,   103.5)))
        asr.get(암종.모든암)?.put(Range.closed(10, 14), mapOf(Pair(Sex.M,   160.1), Pair(Sex.F,   136.3)))
        asr.get(암종.모든암)?.put(Range.closed(15, 19), mapOf(Pair(Sex.M,   203.8), Pair(Sex.F,   184.5)))
        asr.get(암종.모든암)?.put(Range.closed(20, 24), mapOf(Pair(Sex.M,   234.0), Pair(Sex.F,   290.6)))
        asr.get(암종.모든암)?.put(Range.closed(25, 29), mapOf(Pair(Sex.M,   308.4), Pair(Sex.F,   593.0)))
        asr.get(암종.모든암)?.put(Range.closed(30, 34), mapOf(Pair(Sex.M,   495.9), Pair(Sex.F,  1214.1)))
        asr.get(암종.모든암)?.put(Range.closed(35, 39), mapOf(Pair(Sex.M,   807.1), Pair(Sex.F,  2221.5)))
        asr.get(암종.모든암)?.put(Range.closed(40, 44), mapOf(Pair(Sex.M,  1218.4), Pair(Sex.F,  3505.3)))
        asr.get(암종.모든암)?.put(Range.closed(45, 49), mapOf(Pair(Sex.M,  1761.0), Pair(Sex.F,  4938.4)))
        asr.get(암종.모든암)?.put(Range.closed(50, 54), mapOf(Pair(Sex.M,  2779.0), Pair(Sex.F,  6518.1)))
        asr.get(암종.모든암)?.put(Range.closed(55, 59), mapOf(Pair(Sex.M,  4473.3), Pair(Sex.F,  7787.1)))
        asr.get(암종.모든암)?.put(Range.closed(60, 64), mapOf(Pair(Sex.M,  7405.8), Pair(Sex.F,  8998.6)))
        asr.get(암종.모든암)?.put(Range.closed(65, 69), mapOf(Pair(Sex.M, 10933.0), Pair(Sex.F,  9339.1)))
        asr.get(암종.모든암)?.put(Range.closed(70, 74), mapOf(Pair(Sex.M, 15709.0), Pair(Sex.F, 10015.0)))
        asr.get(암종.모든암)?.put(Range.closed(75, 79), mapOf(Pair(Sex.M, 19148.0), Pair(Sex.F, 10019.0)))
        asr.get(암종.모든암)?.put(Range.closed(80, 84), mapOf(Pair(Sex.M, 22052.0), Pair(Sex.F, 10002.0)))
        asr.get(암종.모든암)?.put(Range.closed(85,100), mapOf(Pair(Sex.M, 21703.0), Pair(Sex.F,  8585.7)))

        //endregion
    }
    enum class 암종 {
        폐암, 대장암, 간암, 췌장암, 식도암, 유방암, 난소암, 모든암
    }
}