spring:
  application:
    name: alis
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery:
        root: /avoid-service
server:
  port: 0

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

alis:
  api:
    url: http://gcgenome.labcenter.kr/LabInterfaceService.asmx
    content-type: application/soap+xml; charset=utf-8
    username: interface32
    password: gcpmc9347!$*