spring:
  application:
    name: alis-api
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery:
        root: /avoid-service
  r2dbc:
    url: r2dbc:sqlserver://172.19.208.202:14032/LC32_GCGENOME
    username: interface32
    password: gcpmc9347!$*
server:
  port: 0

logging:
  level:
    io.r2dbc.mssql.QUERY: DEBUG # for queries
    io.r2dbc.mssql.PARAM: DEBUG # for parameters
#    io.r2dbc.mssql.client: TRACE

alis:
  api:
    url: http://gcgenome.labcenter.kr/LabInterfaceService.asmx
    content-type: application/soap+xml; charset=utf-8
    username: interface32
    password: gcpmc9347!$*