spring:
  application.name: avoid-analysis-crawler
  main.web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery.root: /avoid-project
  r2dbc:
    url: r2dbc:postgresql://172.19.216.212:5432/lims
    compatibility-mode : true
    username: postgres
    password: X9ZWLERPs54RRYMic8FXJqV1TobIA2rwqGDgctFj1mQj1aco7TqkLoes9AByUFgW
server:
  port: 0
logging:
  level:
    io.r2dbc.postgresql.QUERY: TRACE
    io.r2dbc.postgresql.PARAM: TRACE
gcgenome:
  tmp-dir: D:\\data\\lims\\tmp
  out-dir: D:\\data\\lims\\avoid-processed

webhook:
  url: https://wh.jandi.com/connect-api/webhook/17558388/69834a4cb47d80f9c339a0ce83ab7c90
