spring:
  application.name: avoid-analysis-crawler
  main.web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery.root: /avoid-project
  r2dbc:
    url: r2dbc:postgresql://gemini:5432/lims
    compatibility-mode: true
    username: avoid
    password: avoid1004
server:
  port: 0
gcgenome:
  tmp-dir: D:\\data\\lims\\tmp
  out-dir: D:\\data\\lims\\avoid-processed