spring:
  application:
    name: report-api
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery:
        root: /avoid-service
    stream:
      function:
        definition: publish-printing; broadcast-printing;
      bindings:
        broadcast-printing-in-0:
          destination: avoid-printing-events
          group: broadcast-printing-events
        publish-printing-out-0:
          destination: avoid-printing-events
      kafka:
        binder:
          brokers: gemini, pisces, aries, taurus, libra
          auto-add-partitions: true
  r2dbc:
    url: r2dbc:postgresql://gemini:5432/lims
    compatibility-mode : true
    username: avoid
    password: avoid1004
  data:
    cassandra:
      contact-points: gemini, pisces, taurus
      local-datacenter: datacenter1
      username: cassandra
      password: snubi1004
      port: 9042
      keyspace-name: lims
      schema-action: NONE
      connect-timeout-millis: 10000s
      read-timeout-millis: 10000s
      connect-timeout: 10000s
      read-timeout: 10000s
      pool-timeout: 10000s
server:
  port: 0

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters