spring:
  application:
    name: report-api
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: localhost:12181
      discovery:
        root: /avoid-service
    stream:
      function:
        definition: publish-printing; broadcast-printing;
      bindings:
        broadcast-printing-in-0:
          destination: avoid-printing-events
          group: broadcast-printing-events
        publish-printing-out-0:
          destination: avoid-printing-events
      kafka:
        binder:
          brokers: localhost
          auto-add-partitions: true
  r2dbc:
    url: r2dbc:postgresql://172.19.216.212:5432/lims
    compatibility-mode : true
    username: avoid
    password: avoid1004
  data:
    cassandra:
      contact-points: 172.19.216.213
      local-datacenter: cassandra
      username: gcgenome-superuser
      password: CvuvlrYXpi75SMjGfCcL7-9dKUIryACXAivIkrspuHszteuDj8weZQ
      port: 9042
      keyspace-name: lims
      schema-action: NONE
      connection:
        connect-timeout: 10000s

server:
  port: 55398

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
