plugins {
    id "org.springframework.boot" version "2.6.6"
}
apply plugin: "java"
apply plugin: "io.spring.dependency-management"

group = "com.greencross"
version = "1.0"
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

repositories {
    mavenCentral()
    mavenLocal()
}
dependencies {
    implementation project(":shared")
    implementation('com.greencross:lims-api-gateway-data:1.0')
    implementation('com.greencross:lims-service-data:1.0')
    implementation('org.springframework.boot:spring-boot-starter-security')
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation('org.springframework.retry:spring-retry')
    implementation("org.springframework.cloud:spring-cloud-starter-zookeeper-discovery")
    implementation('org.springframework.boot:spring-boot-starter-log4j2')
    implementation('org.springframework.boot:spring-boot-starter-data-jpa')
    implementation('org.postgresql:postgresql')
    compileOnly("org.projectlombok:lombok")
    compileOnly("net.sayaya:mapstruct-fluent-accessor:1.0")
    compileOnly("org.mapstruct:mapstruct:1.4.2.Final")
    compileOnly("org.projectlombok:lombok-mapstruct-binding:0.2.0")
    annotationProcessor("org.projectlombok:lombok")
    annotationProcessor("net.sayaya:mapstruct-fluent-accessor:1.0")
    annotationProcessor("org.mapstruct:mapstruct-processor:1.4.2.Final")
    annotationProcessor("org.projectlombok:lombok-mapstruct-binding:0.2.0")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("io.projectreactor:reactor-test")
    implementation("io.springfox:springfox-boot-starter:3.0.0")
    implementation("io.springfox:springfox-swagger-ui")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2021.0.0"
    }
}
configurations {
    all*.exclude group:'org.springframework.boot', module:'spring-boot-starter-logging'
}
task copyWebResources(type: Copy) {
    dependsOn ":analysis-ui:build"
    from(zipTree ('../analysis-ui/build/libs/avoid-analysis.war')) {
        include '**/*.js'
        include '**/*.css'
        include '**/*.png'
        include '**/*.gif'
        include '**/*.wav'
        include '**/*.ogg'
        include '**/*.svg'
        include '**/*.ttf'
        include '**/*.woff'
        include '**/*.woff2'
        include '**/*.eot'
        include '*.html'
        includeEmptyDirs = false
    }
    into "src/main/resources/static"
}
processResources {
    dependsOn copyWebResources
    if(project.gradle.startParameter.taskNames.contains("build")) exclude("application.yml")
}
bootJar {
    archiveFileName = "avoid-analysis.jar"
}
clean.doFirst {
    delete "src/main/resources/static"
    delete "build/"
}
test {
    useJUnitPlatform()
}