spring:
  application:
    name: worklist-service
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery:
        root: /RnD
  r2dbc:
    url: r2dbc:postgresql://gemini:5432/lims
    username: rnd
    password: rnd1004!@
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
server:
  port: 0
  temp-directory: D:\data\rnd\worklist