spring:
  application:
    name: worklist-service
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: gemini:2181,pisces:2181,aries:2181,taurus:2181
      discovery:
        root: /RnD
    stream:
      kafka:
        binder:
          brokers: gemini, pisces, aries, taurus, libra
          auto-add-partitions: true
  r2dbc:
    url: r2dbc:postgresql://gemini:5432/lims
    username: rnd
    password: rnd1004!@
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
server:
  port: 0
  temp-directory: /data/lims/tmp/RnD/worklist